// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAJYoz-3VnlZsLSKhk3IYcnknXs3k3J_s',
    appId: '1:1027722670631:web:2d1c5360ecc53f0253d402',
    messagingSenderId: '1027722670631',
    projectId: 'exemplo1-45bc6',
    authDomain: 'exemplo1-45bc6.firebaseapp.com',
    databaseURL: 'https://exemplo1-45bc6-default-rtdb.firebaseio.com',
    storageBucket: 'exemplo1-45bc6.appspot.com',
    measurementId: 'G-S4YS60ZJ0T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJJ4ZKIKi6sZxqYBK1hnUtHDzAFd5ZT64',
    appId: '1:1027722670631:android:25e63a0815d6ae6753d402',
    messagingSenderId: '1027722670631',
    projectId: 'exemplo1-45bc6',
    databaseURL: 'https://exemplo1-45bc6-default-rtdb.firebaseio.com',
    storageBucket: 'exemplo1-45bc6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9O7jY0geh9WvX2CY3Addq97Hy6Dxylm8',
    appId: '1:1027722670631:ios:5dfdafdc42b8e7a453d402',
    messagingSenderId: '1027722670631',
    projectId: 'exemplo1-45bc6',
    databaseURL: 'https://exemplo1-45bc6-default-rtdb.firebaseio.com',
    storageBucket: 'exemplo1-45bc6.appspot.com',
    iosClientId: '1027722670631-ivn5bmj370js486gj2s87stgufo4eh5h.apps.googleusercontent.com',
    iosBundleId: 'com.example.projeto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9O7jY0geh9WvX2CY3Addq97Hy6Dxylm8',
    appId: '1:1027722670631:ios:5dfdafdc42b8e7a453d402',
    messagingSenderId: '1027722670631',
    projectId: 'exemplo1-45bc6',
    databaseURL: 'https://exemplo1-45bc6-default-rtdb.firebaseio.com',
    storageBucket: 'exemplo1-45bc6.appspot.com',
    iosClientId: '1027722670631-ivn5bmj370js486gj2s87stgufo4eh5h.apps.googleusercontent.com',
    iosBundleId: 'com.example.projeto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZz7m2I10nB8FS3KtcOjY47Xo6rBJTnmc',
    appId: '1:1027722670631:web:8eb59e708e8531c853d402',
    messagingSenderId: '1027722670631',
    projectId: 'exemplo1-45bc6',
    authDomain: 'exemplo1-45bc6.firebaseapp.com',
    databaseURL: 'https://exemplo1-45bc6-default-rtdb.firebaseio.com',
    storageBucket: 'exemplo1-45bc6.appspot.com',
    measurementId: 'G-M8FZN4WBZG',
  );

}